name: Duolingo XP Farmer
on:
  schedule:
    - cron: '1 22 * * *' # Runs at 00:01 Romania Time
  workflow_dispatch:
jobs:
  run-xp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Execute Script
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ secrets.LESSONS }}
        run: node duolingo.js